---
- name: Template nagios.cfg
  template:
    src: templates/nagios.cfg.j2
    dest: /etc/nagios/nagios.cfg

- name: Make sure the /etc/nagios/servers folder exists
  file:
    path: /etc/nagios/servers
    state: directory

- name: Template object file
  template:
    src: templates/object.cfg.j2
    dest: /etc/nagios/servers/{{ item }}.cfg
  with_items: "{{ groups['all'] }}"
  notify: [ 'Bounce nagios' ]
